version: "3.8"

services:
  api_gateway:
    build:
      context: ./api_gateway
    ports:
      - "8000:8000"
    volumes:
      - ./api_gateway:/app
    environment:
      - PYTHONUNBUFFERED=1
    container_name: rt_tar_api_gateway
